mybatis:
  type-aliases-package: com.yefeng.pojo
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 500
    default-statement-timeout: 80
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bishe?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    password: 199712
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root

jedis:
  pool:
    host: 127.0.0.1
    port: 6379
  config:
    maxTotal: 100
    maxIdle: 10
    maxWaitMillis: 100000

logging:
  level: warn
multipart:
  max-request-size: 100MB
  max-file-size: 20MB

fileUpload:
  filePath: E:/video-file

ffmpegPath: D:/FFmpeg/ffmpeg/bin/ffmpeg.exe
